import { MockData } from "./types";

// Restructured mock data: class → subject → chapters
export const mockData: MockData = {
  chapters: {
    "8th": {
      Mathematics: [
        {
          id: "math_8_ch1",
          title: "Rational Numbers",
          subject: "Mathematics",
          classLevel: "8th",
          description: "Understanding rational numbers and their operations",
          topics: [
            {
              id: "topic_1_1",
              title: "Introduction to Rational Numbers",
              chapterId: "math_8_ch1",
              order: 1,
            },
            {
              id: "topic_1_2",
              title: "Properties of Rational Numbers",
              chapterId: "math_8_ch1",
              order: 2,
            },
            {
              id: "topic_1_3",
              title: "Operations on Rational Numbers",
              chapterId: "math_8_ch1",
              order: 3,
            },
          ],
        },
        {
          id: "math_8_ch2",
          title: "Linear Equations in One Variable",
          subject: "Mathematics",
          classLevel: "8th",
          description: "Solving linear equations with one variable",
          topics: [
            {
              id: "topic_2_1",
              title: "Introduction to Linear Equations",
              chapterId: "math_8_ch2",
              order: 1,
            },
            {
              id: "topic_2_2",
              title: "Solving Linear Equations",
              chapterId: "math_8_ch2",
              order: 2,
            },
            {
              id: "topic_2_3",
              title: "Applications of Linear Equations",
              chapterId: "math_8_ch2",
              order: 3,
            },
          ],
        },
        {
          id: "math_8_ch3",
          title: "Understanding Quadrilaterals",
          subject: "Mathematics",
          classLevel: "8th",
          description: "Properties and types of quadrilaterals",
          topics: [
            {
              id: "topic_3_1",
              title: "Introduction to Quadrilaterals",
              chapterId: "math_8_ch3",
              order: 1,
            },
            {
              id: "topic_3_2",
              title: "Types of Quadrilaterals",
              chapterId: "math_8_ch3",
              order: 2,
            },
            {
              id: "topic_3_3",
              title: "Properties of Parallelograms",
              chapterId: "math_8_ch3",
              order: 3,
            },
          ],
        },
      ],
      Science: [
        {
          id: "sci_8_ch1",
          title: "Crop Production and Management",
          subject: "Science",
          classLevel: "8th",
          description: "Agricultural practices and crop management",
          topics: [
            {
              id: "topic_sci_8_1_1",
              title: "Agricultural Practices",
              chapterId: "sci_8_ch1",
              order: 1,
            },
            {
              id: "topic_sci_8_1_2",
              title: "Basic Practices of Crop Production",
              chapterId: "sci_8_ch1",
              order: 2,
            },
            {
              id: "topic_sci_8_1_3",
              title: "Preparation of Soil",
              chapterId: "sci_8_ch1",
              order: 3,
            },
          ],
        },
        {
          id: "sci_8_ch2",
          title: "Microorganisms: Friend and Foe",
          subject: "Science",
          classLevel: "8th",
          description: "Understanding microorganisms and their effects",
          topics: [
            {
              id: "topic_sci_8_2_1",
              title: "Microorganisms and Us",
              chapterId: "sci_8_ch2",
              order: 1,
            },
            {
              id: "topic_sci_8_2_2",
              title: "Where Do Microorganisms Live?",
              chapterId: "sci_8_ch2",
              order: 2,
            },
            {
              id: "topic_sci_8_2_3",
              title: "Microorganisms and Disease",
              chapterId: "sci_8_ch2",
              order: 3,
            },
          ],
        },
      ],
      English: [
        {
          id: "eng_8_ch1",
          title: "The Best Christmas Present in the World",
          subject: "English",
          classLevel: "8th",
          description: "A touching story about war and humanity",
          topics: [
            {
              id: "topic_eng_8_1_1",
              title: "Character Analysis",
              chapterId: "eng_8_ch1",
              order: 1,
            },
            {
              id: "topic_eng_8_1_2",
              title: "Theme and Message",
              chapterId: "eng_8_ch1",
              order: 2,
            },
            {
              id: "topic_eng_8_1_3",
              title: "Literary Devices",
              chapterId: "eng_8_ch1",
              order: 3,
            },
          ],
        },
        {
          id: "eng_8_ch2",
          title: "The Tsunami",
          subject: "English",
          classLevel: "8th",
          description:
            "Stories of survival and courage during natural disasters",
          topics: [
            {
              id: "topic_eng_8_2_1",
              title: "Understanding Natural Disasters",
              chapterId: "eng_8_ch2",
              order: 1,
            },
            {
              id: "topic_eng_8_2_2",
              title: "Human Response to Crisis",
              chapterId: "eng_8_ch2",
              order: 2,
            },
          ],
        },
      ],
      "Social Science": [],
    },
    "9th": {
      Mathematics: [
        {
          id: "math_9_ch1",
          title: "Number Systems",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Real Numbers, Irrational Numbers, Laws of Exponents",
          weightage: 6,
          topics: [
            {
              id: "topic_math_9_1_1",
              title: "Real Numbers",
              chapterId: "math_9_ch1",
              order: 1,
            },
            {
              id: "topic_math_9_1_2",
              title: "Irrational Numbers",
              chapterId: "math_9_ch1",
              order: 2,
            },
            {
              id: "topic_math_9_1_3",
              title: "Laws of Exponents",
              chapterId: "math_9_ch1",
              order: 3,
            },
          ],
        },
        {
          id: "math_9_ch2",
          title: "Polynomials",
          subject: "Mathematics",
          classLevel: "9th",
          description:
            "Degree, Coefficients, Factor Theorem, Remainder Theorem",
          weightage: 4,
          topics: [
            {
              id: "topic_math_9_2_1",
              title: "Degree",
              chapterId: "math_9_ch2",
              order: 1,
            },
            {
              id: "topic_math_9_2_2",
              title: "Coefficients",
              chapterId: "math_9_ch2",
              order: 2,
            },
            {
              id: "topic_math_9_2_3",
              title: "Factor Theorem",
              chapterId: "math_9_ch2",
              order: 3,
            },
            {
              id: "topic_math_9_2_4",
              title: "Remainder Theorem",
              chapterId: "math_9_ch2",
              order: 4,
            },
          ],
        },
        {
          id: "math_9_ch3",
          title: "Coordinate Geometry",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Cartesian Plane, Plotting Points, Quadrants",
          weightage: 4,
          topics: [
            {
              id: "topic_math_9_3_1",
              title: "Cartesian Plane",
              chapterId: "math_9_ch3",
              order: 1,
            },
            {
              id: "topic_math_9_3_2",
              title: "Plotting Points",
              chapterId: "math_9_ch3",
              order: 2,
            },
            {
              id: "topic_math_9_3_3",
              title: "Quadrants",
              chapterId: "math_9_ch3",
              order: 3,
            },
          ],
        },
        {
          id: "math_9_ch4",
          title: "Linear Equations in Two Variables",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Graph of Linear Equations, Solutions, Applications",
          weightage: 6,
          topics: [
            {
              id: "topic_math_9_4_1",
              title: "Graph of Linear Equations",
              chapterId: "math_9_ch4",
              order: 1,
            },
            {
              id: "topic_math_9_4_2",
              title: "Solutions",
              chapterId: "math_9_ch4",
              order: 2,
            },
            {
              id: "topic_math_9_4_3",
              title: "Applications",
              chapterId: "math_9_ch4",
              order: 3,
            },
          ],
        },
        {
          id: "math_9_ch5",
          title: "Introduction to Euclid's Geometry",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Euclid's Postulates, Axioms, Basic Definitions",
          weightage: 2,
          topics: [
            {
              id: "topic_math_9_5_1",
              title: "Euclid's Postulates",
              chapterId: "math_9_ch5",
              order: 1,
            },
            {
              id: "topic_math_9_5_2",
              title: "Axioms",
              chapterId: "math_9_ch5",
              order: 2,
            },
            {
              id: "topic_math_9_5_3",
              title: "Basic Definitions",
              chapterId: "math_9_ch5",
              order: 3,
            },
          ],
        },
        {
          id: "math_9_ch6",
          title: "Lines and Angles",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Types of Angles, Axioms & Theorems, Parallel Lines",
          weightage: 6,
          topics: [
            {
              id: "topic_math_9_6_1",
              title: "Types of Angles",
              chapterId: "math_9_ch6",
              order: 1,
            },
            {
              id: "topic_math_9_6_2",
              title: "Axioms & Theorems",
              chapterId: "math_9_ch6",
              order: 2,
            },
            {
              id: "topic_math_9_6_3",
              title: "Parallel Lines",
              chapterId: "math_9_ch6",
              order: 3,
            },
          ],
        },
        {
          id: "math_9_ch7",
          title: "Triangles",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Congruence Criteria, Inequalities in Triangles",
          weightage: 8,
          topics: [
            {
              id: "topic_math_9_7_1",
              title: "Congruence Criteria",
              chapterId: "math_9_ch7",
              order: 1,
            },
            {
              id: "topic_math_9_7_2",
              title: "Inequalities in Triangles",
              chapterId: "math_9_ch7",
              order: 2,
            },
          ],
        },
        {
          id: "math_9_ch8",
          title: "Quadrilaterals",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Properties, Parallelogram Theorems, Angle Sum Property",
          weightage: 6,
          topics: [
            {
              id: "topic_math_9_8_1",
              title: "Properties",
              chapterId: "math_9_ch8",
              order: 1,
            },
            {
              id: "topic_math_9_8_2",
              title: "Parallelogram Theorems",
              chapterId: "math_9_ch8",
              order: 2,
            },
            {
              id: "topic_math_9_8_3",
              title: "Angle Sum Property",
              chapterId: "math_9_ch8",
              order: 3,
            },
          ],
        },
        {
          id: "math_9_ch9",
          title: "Areas of Parallelograms and Triangles",
          subject: "Mathematics",
          classLevel: "9th",
          description:
            "Theorems on Areas, Parallelogram on Same Base, Triangle Properties",
          weightage: 4,
          topics: [
            {
              id: "topic_math_9_9_1",
              title: "Theorems on Areas",
              chapterId: "math_9_ch9",
              order: 1,
            },
            {
              id: "topic_math_9_9_2",
              title: "Parallelogram on Same Base",
              chapterId: "math_9_ch9",
              order: 2,
            },
            {
              id: "topic_math_9_9_3",
              title: "Triangle Properties",
              chapterId: "math_9_ch9",
              order: 3,
            },
          ],
        },
        {
          id: "math_9_ch10",
          title: "Circles",
          subject: "Mathematics",
          classLevel: "9th",
          description:
            "Radius, Diameter, Chord Properties, Cyclic Quadrilateral",
          weightage: 6,
          topics: [
            {
              id: "topic_math_9_10_1",
              title: "Radius",
              chapterId: "math_9_ch10",
              order: 1,
            },
            {
              id: "topic_math_9_10_2",
              title: "Diameter",
              chapterId: "math_9_ch10",
              order: 2,
            },
            {
              id: "topic_math_9_10_3",
              title: "Chord Properties",
              chapterId: "math_9_ch10",
              order: 3,
            },
            {
              id: "topic_math_9_10_4",
              title: "Cyclic Quadrilateral",
              chapterId: "math_9_ch10",
              order: 4,
            },
          ],
        },
        {
          id: "math_9_ch11",
          title: "Constructions",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Division of a Line Segment, Angle Bisector",
          weightage: 4,
          topics: [
            {
              id: "topic_math_9_11_1",
              title: "Division of a Line Segment",
              chapterId: "math_9_ch11",
              order: 1,
            },
            {
              id: "topic_math_9_11_2",
              title: "Angle Bisector",
              chapterId: "math_9_ch11",
              order: 2,
            },
          ],
        },
        {
          id: "math_9_ch12",
          title: "Heron's Formula",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Area of Triangles Using Heron's Formula",
          weightage: 4,
          topics: [
            {
              id: "topic_math_9_12_1",
              title: "Area of Triangles Using Heron's Formula",
              chapterId: "math_9_ch12",
              order: 1,
            },
          ],
        },
        {
          id: "math_9_ch13",
          title: "Surface Areas and Volumes",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Cubes, Cuboids, Cylinders, Cones, Spheres",
          weightage: 8,
          topics: [
            {
              id: "topic_math_9_13_1",
              title: "Cubes",
              chapterId: "math_9_ch13",
              order: 1,
            },
            {
              id: "topic_math_9_13_2",
              title: "Cuboids",
              chapterId: "math_9_ch13",
              order: 2,
            },
            {
              id: "topic_math_9_13_3",
              title: "Cylinders",
              chapterId: "math_9_ch13",
              order: 3,
            },
            {
              id: "topic_math_9_13_4",
              title: "Cones",
              chapterId: "math_9_ch13",
              order: 4,
            },
            {
              id: "topic_math_9_13_5",
              title: "Spheres",
              chapterId: "math_9_ch13",
              order: 5,
            },
          ],
        },
        {
          id: "math_9_ch14",
          title: "Statistics",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Mean, Median, Mode, Bar Graphs, Histogram",
          weightage: 6,
          topics: [
            {
              id: "topic_math_9_14_1",
              title: "Mean",
              chapterId: "math_9_ch14",
              order: 1,
            },
            {
              id: "topic_math_9_14_2",
              title: "Median",
              chapterId: "math_9_ch14",
              order: 2,
            },
            {
              id: "topic_math_9_14_3",
              title: "Mode",
              chapterId: "math_9_ch14",
              order: 3,
            },
            {
              id: "topic_math_9_14_4",
              title: "Bar Graphs",
              chapterId: "math_9_ch14",
              order: 4,
            },
            {
              id: "topic_math_9_14_5",
              title: "Histogram",
              chapterId: "math_9_ch14",
              order: 5,
            },
          ],
        },
        {
          id: "math_9_ch15",
          title: "Probability",
          subject: "Mathematics",
          classLevel: "9th",
          description: "Experimental Probability, Simple Events",
          weightage: 4,
          topics: [
            {
              id: "topic_math_9_15_1",
              title: "Experimental Probability",
              chapterId: "math_9_ch15",
              order: 1,
            },
            {
              id: "topic_math_9_15_2",
              title: "Simple Events",
              chapterId: "math_9_ch15",
              order: 2,
            },
          ],
        },
      ],
      Science: [
        {
          id: "sci_9_ch1",
          title: "Matter in Our Surroundings",
          subject: "Science",
          classLevel: "9th",
          description: "States of Matter, Evaporation, Latent Heat",
          weightage: 5,
          topics: [
            {
              id: "topic_sci_9_1_1",
              title: "States of Matter",
              chapterId: "sci_9_ch1",
              order: 1,
            },
            {
              id: "topic_sci_9_1_2",
              title: "Evaporation",
              chapterId: "sci_9_ch1",
              order: 2,
            },
            {
              id: "topic_sci_9_1_3",
              title: "Latent Heat",
              chapterId: "sci_9_ch1",
              order: 3,
            },
          ],
        },
        {
          id: "sci_9_ch2",
          title: "Is Matter Around Us Pure",
          subject: "Science",
          classLevel: "9th",
          description: "Mixtures, Solutions, Separation Techniques",
          weightage: 5,
          topics: [
            {
              id: "topic_sci_9_2_1",
              title: "Mixtures",
              chapterId: "sci_9_ch2",
              order: 1,
            },
            {
              id: "topic_sci_9_2_2",
              title: "Solutions",
              chapterId: "sci_9_ch2",
              order: 2,
            },
            {
              id: "topic_sci_9_2_3",
              title: "Separation Techniques",
              chapterId: "sci_9_ch2",
              order: 3,
            },
          ],
        },
        {
          id: "sci_9_ch3",
          title: "Atoms and Molecules",
          subject: "Science",
          classLevel: "9th",
          description: "Laws of Chemical Combination, Mole Concept",
          weightage: 7,
          topics: [
            {
              id: "topic_sci_9_3_1",
              title: "Laws of Chemical Combination",
              chapterId: "sci_9_ch3",
              order: 1,
            },
            {
              id: "topic_sci_9_3_2",
              title: "Mole Concept",
              chapterId: "sci_9_ch3",
              order: 2,
            },
          ],
        },
        {
          id: "sci_9_ch4",
          title: "Structure of the Atom",
          subject: "Science",
          classLevel: "9th",
          description:
            "Subatomic Particles, Atomic Models, Electronic Configuration",
          weightage: 6,
          topics: [
            {
              id: "topic_sci_9_4_1",
              title: "Subatomic Particles",
              chapterId: "sci_9_ch4",
              order: 1,
            },
            {
              id: "topic_sci_9_4_2",
              title: "Atomic Models",
              chapterId: "sci_9_ch4",
              order: 2,
            },
            {
              id: "topic_sci_9_4_3",
              title: "Electronic Configuration",
              chapterId: "sci_9_ch4",
              order: 3,
            },
          ],
        },
        {
          id: "sci_9_ch5",
          title: "The Fundamental Unit of Life",
          subject: "Science",
          classLevel: "9th",
          description: "Cell Structure, Organelles, Plant vs Animal Cells",
          weightage: 6,
          topics: [
            {
              id: "topic_sci_9_5_1",
              title: "Cell Structure",
              chapterId: "sci_9_ch5",
              order: 1,
            },
            {
              id: "topic_sci_9_5_2",
              title: "Organelles",
              chapterId: "sci_9_ch5",
              order: 2,
            },
            {
              id: "topic_sci_9_5_3",
              title: "Plant vs Animal Cells",
              chapterId: "sci_9_ch5",
              order: 3,
            },
          ],
        },
        {
          id: "sci_9_ch6",
          title: "Tissues",
          subject: "Science",
          classLevel: "9th",
          description: "Plant and Animal Tissues, Functions, Types",
          weightage: 6,
          topics: [
            {
              id: "topic_sci_9_6_1",
              title: "Plant Tissues",
              chapterId: "sci_9_ch6",
              order: 1,
            },
            {
              id: "topic_sci_9_6_2",
              title: "Animal Tissues",
              chapterId: "sci_9_ch6",
              order: 2,
            },
            {
              id: "topic_sci_9_6_3",
              title: "Functions",
              chapterId: "sci_9_ch6",
              order: 3,
            },
            {
              id: "topic_sci_9_6_4",
              title: "Types",
              chapterId: "sci_9_ch6",
              order: 4,
            },
          ],
        },
        {
          id: "sci_9_ch7",
          title: "Motion",
          subject: "Science",
          classLevel: "9th",
          description: "Distance, Displacement, Speed, Velocity, Graphs",
          weightage: 8,
          topics: [
            {
              id: "topic_sci_9_7_1",
              title: "Distance",
              chapterId: "sci_9_ch7",
              order: 1,
            },
            {
              id: "topic_sci_9_7_2",
              title: "Displacement",
              chapterId: "sci_9_ch7",
              order: 2,
            },
            {
              id: "topic_sci_9_7_3",
              title: "Speed",
              chapterId: "sci_9_ch7",
              order: 3,
            },
            {
              id: "topic_sci_9_7_4",
              title: "Velocity",
              chapterId: "sci_9_ch7",
              order: 4,
            },
            {
              id: "topic_sci_9_7_5",
              title: "Graphs",
              chapterId: "sci_9_ch7",
              order: 5,
            },
          ],
        },
        {
          id: "sci_9_ch8",
          title: "Force and Laws of Motion",
          subject: "Science",
          classLevel: "9th",
          description: "Newton's Laws, Inertia, Momentum",
          weightage: 8,
          topics: [
            {
              id: "topic_sci_9_8_1",
              title: "Newton's Laws",
              chapterId: "sci_9_ch8",
              order: 1,
            },
            {
              id: "topic_sci_9_8_2",
              title: "Inertia",
              chapterId: "sci_9_ch8",
              order: 2,
            },
            {
              id: "topic_sci_9_8_3",
              title: "Momentum",
              chapterId: "sci_9_ch8",
              order: 3,
            },
          ],
        },
        {
          id: "sci_9_ch9",
          title: "Gravitation",
          subject: "Science",
          classLevel: "9th",
          description: "Universal Law of Gravitation, Free Fall, Buoyancy",
          weightage: 6,
          topics: [
            {
              id: "topic_sci_9_9_1",
              title: "Universal Law of Gravitation",
              chapterId: "sci_9_ch9",
              order: 1,
            },
            {
              id: "topic_sci_9_9_2",
              title: "Free Fall",
              chapterId: "sci_9_ch9",
              order: 2,
            },
            {
              id: "topic_sci_9_9_3",
              title: "Buoyancy",
              chapterId: "sci_9_ch9",
              order: 3,
            },
          ],
        },
        {
          id: "sci_9_ch10",
          title: "Work and Energy",
          subject: "Science",
          classLevel: "9th",
          description: "Work, Energy, Power, Law of Conservation of Energy",
          weightage: 7,
          topics: [
            {
              id: "topic_sci_9_10_1",
              title: "Work",
              chapterId: "sci_9_ch10",
              order: 1,
            },
            {
              id: "topic_sci_9_10_2",
              title: "Energy",
              chapterId: "sci_9_ch10",
              order: 2,
            },
            {
              id: "topic_sci_9_10_3",
              title: "Power",
              chapterId: "sci_9_ch10",
              order: 3,
            },
            {
              id: "topic_sci_9_10_4",
              title: "Law of Conservation of Energy",
              chapterId: "sci_9_ch10",
              order: 4,
            },
          ],
        },
        {
          id: "sci_9_ch11",
          title: "Sound",
          subject: "Science",
          classLevel: "9th",
          description: "Wave Motion, Speed of Sound, Echo, Reflection",
          weightage: 7,
          topics: [
            {
              id: "topic_sci_9_11_1",
              title: "Wave Motion",
              chapterId: "sci_9_ch11",
              order: 1,
            },
            {
              id: "topic_sci_9_11_2",
              title: "Speed of Sound",
              chapterId: "sci_9_ch11",
              order: 2,
            },
            {
              id: "topic_sci_9_11_3",
              title: "Echo",
              chapterId: "sci_9_ch11",
              order: 3,
            },
            {
              id: "topic_sci_9_11_4",
              title: "Reflection",
              chapterId: "sci_9_ch11",
              order: 4,
            },
          ],
        },
        {
          id: "sci_9_ch12",
          title: "Why Do We Fall Ill",
          subject: "Science",
          classLevel: "9th",
          description: "Health & Diseases, Immunity, Prevention",
          weightage: 5,
          topics: [
            {
              id: "topic_sci_9_12_1",
              title: "Health & Diseases",
              chapterId: "sci_9_ch12",
              order: 1,
            },
            {
              id: "topic_sci_9_12_2",
              title: "Immunity",
              chapterId: "sci_9_ch12",
              order: 2,
            },
            {
              id: "topic_sci_9_12_3",
              title: "Prevention",
              chapterId: "sci_9_ch12",
              order: 3,
            },
          ],
        },
        {
          id: "sci_9_ch13",
          title: "Natural Resources",
          subject: "Science",
          classLevel: "9th",
          description: "Air, Water, Soil, Biogeochemical Cycles",
          weightage: 4,
          topics: [
            {
              id: "topic_sci_9_13_1",
              title: "Air",
              chapterId: "sci_9_ch13",
              order: 1,
            },
            {
              id: "topic_sci_9_13_2",
              title: "Water",
              chapterId: "sci_9_ch13",
              order: 2,
            },
            {
              id: "topic_sci_9_13_3",
              title: "Soil",
              chapterId: "sci_9_ch13",
              order: 3,
            },
            {
              id: "topic_sci_9_13_4",
              title: "Biogeochemical Cycles",
              chapterId: "sci_9_ch13",
              order: 4,
            },
          ],
        },
        {
          id: "sci_9_ch14",
          title: "Improvement in Food Resources",
          subject: "Science",
          classLevel: "9th",
          description:
            "Crop Production, Manure and Fertilizers, Animal Husbandry",
          weightage: 6,
          topics: [
            {
              id: "topic_sci_9_14_1",
              title: "Crop Production",
              chapterId: "sci_9_ch14",
              order: 1,
            },
            {
              id: "topic_sci_9_14_2",
              title: "Manure and Fertilizers",
              chapterId: "sci_9_ch14",
              order: 2,
            },
            {
              id: "topic_sci_9_14_3",
              title: "Animal Husbandry",
              chapterId: "sci_9_ch14",
              order: 3,
            },
          ],
        },
      ],
      English: [
        {
          id: "eng_9_ch1",
          title: "The Fun They Had",
          subject: "English",
          classLevel: "9th",
          description: "A futuristic story about education and technology",
          topics: [
            {
              id: "topic_eng_9_1_1",
              title: "Story Analysis",
              chapterId: "eng_9_ch1",
              order: 1,
            },
            {
              id: "topic_eng_9_1_2",
              title: "Technology and Education",
              chapterId: "eng_9_ch1",
              order: 2,
            },
            {
              id: "topic_eng_9_1_3",
              title: "Character Development",
              chapterId: "eng_9_ch1",
              order: 3,
            },
          ],
        },
        {
          id: "eng_9_ch2",
          title: "The Sound of Music",
          subject: "English",
          classLevel: "9th",
          description: "Stories of musical passion and determination",
          topics: [
            {
              id: "topic_eng_9_2_1",
              title: "Evelyn Glennie's Story",
              chapterId: "eng_9_ch2",
              order: 1,
            },
            {
              id: "topic_eng_9_2_2",
              title: "The Shehnai of Bismillah Khan",
              chapterId: "eng_9_ch2",
              order: 2,
            },
          ],
        },
      ],
    },
    "10th": {
      Mathematics: [
        {
          id: "math_10_ch1",
          title: "Real Numbers",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Euclid's Division Lemma, HCF & LCM, Prime Factorization, Properties of Irrational Numbers",
          weightage: 4,
          topics: [
            {
              id: "topic_math_10_1_1",
              title: "Euclid's Division Lemma",
              chapterId: "math_10_ch1",
              order: 1,
            },
            {
              id: "topic_math_10_1_2",
              title: "HCF & LCM",
              chapterId: "math_10_ch1",
              order: 2,
            },
            {
              id: "topic_math_10_1_3",
              title: "Prime Factorization",
              chapterId: "math_10_ch1",
              order: 3,
            },
            {
              id: "topic_math_10_1_4",
              title: "Properties of Irrational Numbers",
              chapterId: "math_10_ch1",
              order: 4,
            },
          ],
        },
        {
          id: "math_10_ch2",
          title: "Polynomials",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Zeroes of a Polynomial, Relationship between Zeroes and Coefficients, Graph of Quadratic Polynomial",
          weightage: 3,
          topics: [
            {
              id: "topic_math_10_2_1",
              title: "Zeroes of a Polynomial",
              chapterId: "math_10_ch2",
              order: 1,
            },
            {
              id: "topic_math_10_2_2",
              title: "Relationship between Zeroes and Coefficients",
              chapterId: "math_10_ch2",
              order: 2,
            },
            {
              id: "topic_math_10_2_3",
              title: "Graph of Quadratic Polynomial",
              chapterId: "math_10_ch2",
              order: 3,
            },
          ],
        },
        {
          id: "math_10_ch3",
          title: "Pair of Linear Equations in Two Variables",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Graphical Method, Substitution, Elimination, Cross Multiplication",
          weightage: 6,
          topics: [
            {
              id: "topic_math_10_3_1",
              title: "Graphical Method",
              chapterId: "math_10_ch3",
              order: 1,
            },
            {
              id: "topic_math_10_3_2",
              title: "Substitution",
              chapterId: "math_10_ch3",
              order: 2,
            },
            {
              id: "topic_math_10_3_3",
              title: "Elimination",
              chapterId: "math_10_ch3",
              order: 3,
            },
            {
              id: "topic_math_10_3_4",
              title: "Cross Multiplication",
              chapterId: "math_10_ch3",
              order: 4,
            },
          ],
        },
        {
          id: "math_10_ch4",
          title: "Quadratic Equations",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Factorization, Completing the Square, Quadratic Formula, Word Problems",
          weightage: 6,
          topics: [
            {
              id: "topic_math_10_4_1",
              title: "Factorization",
              chapterId: "math_10_ch4",
              order: 1,
            },
            {
              id: "topic_math_10_4_2",
              title: "Completing the Square",
              chapterId: "math_10_ch4",
              order: 2,
            },
            {
              id: "topic_math_10_4_3",
              title: "Quadratic Formula",
              chapterId: "math_10_ch4",
              order: 3,
            },
            {
              id: "topic_math_10_4_4",
              title: "Word Problems",
              chapterId: "math_10_ch4",
              order: 4,
            },
          ],
        },
        {
          id: "math_10_ch5",
          title: "Arithmetic Progressions",
          subject: "Mathematics",
          classLevel: "10th",
          description: "nth Term, Sum of n Terms, Word Problems",
          weightage: 4,
          topics: [
            {
              id: "topic_math_10_5_1",
              title: "nth Term",
              chapterId: "math_10_ch5",
              order: 1,
            },
            {
              id: "topic_math_10_5_2",
              title: "Sum of n Terms",
              chapterId: "math_10_ch5",
              order: 2,
            },
            {
              id: "topic_math_10_5_3",
              title: "Word Problems",
              chapterId: "math_10_ch5",
              order: 3,
            },
          ],
        },
        {
          id: "math_10_ch6",
          title: "Triangles",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Basic Proportionality Theorem, Pythagoras Theorem, Similarity, Area Ratios",
          weightage: 6,
          topics: [
            {
              id: "topic_math_10_6_1",
              title: "Basic Proportionality Theorem",
              chapterId: "math_10_ch6",
              order: 1,
            },
            {
              id: "topic_math_10_6_2",
              title: "Pythagoras Theorem",
              chapterId: "math_10_ch6",
              order: 2,
            },
            {
              id: "topic_math_10_6_3",
              title: "Similarity",
              chapterId: "math_10_ch6",
              order: 3,
            },
            {
              id: "topic_math_10_6_4",
              title: "Area Ratios",
              chapterId: "math_10_ch6",
              order: 4,
            },
          ],
        },
        {
          id: "math_10_ch7",
          title: "Coordinate Geometry",
          subject: "Mathematics",
          classLevel: "10th",
          description: "Distance Formula, Section Formula, Area of Triangle",
          weightage: 6,
          topics: [
            {
              id: "topic_math_10_7_1",
              title: "Distance Formula",
              chapterId: "math_10_ch7",
              order: 1,
            },
            {
              id: "topic_math_10_7_2",
              title: "Section Formula",
              chapterId: "math_10_ch7",
              order: 2,
            },
            {
              id: "topic_math_10_7_3",
              title: "Area of Triangle",
              chapterId: "math_10_ch7",
              order: 3,
            },
          ],
        },
        {
          id: "math_10_ch8",
          title: "Introduction to Trigonometry",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Trigonometric Ratios of Standard Angles, Trigonometric Identities",
          weightage: 6,
          topics: [
            {
              id: "topic_math_10_8_1",
              title: "Trigonometric Ratios of Standard Angles",
              chapterId: "math_10_ch8",
              order: 1,
            },
            {
              id: "topic_math_10_8_2",
              title: "Trigonometric Identities",
              chapterId: "math_10_ch8",
              order: 2,
            },
          ],
        },
        {
          id: "math_10_ch9",
          title: "Applications of Trigonometry",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Heights and Distances (Angle of Elevation and Depression)",
          weightage: 3,
          topics: [
            {
              id: "topic_math_10_9_1",
              title: "Heights and Distances",
              chapterId: "math_10_ch9",
              order: 1,
            },
            {
              id: "topic_math_10_9_2",
              title: "Angle of Elevation",
              chapterId: "math_10_ch9",
              order: 2,
            },
            {
              id: "topic_math_10_9_3",
              title: "Angle of Depression",
              chapterId: "math_10_ch9",
              order: 3,
            },
          ],
        },
        {
          id: "math_10_ch10",
          title: "Circles",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Tangent Properties, Tangent to a Circle from an External Point",
          weightage: 3,
          topics: [
            {
              id: "topic_math_10_10_1",
              title: "Tangent Properties",
              chapterId: "math_10_ch10",
              order: 1,
            },
            {
              id: "topic_math_10_10_2",
              title: "Tangent to a Circle from an External Point",
              chapterId: "math_10_ch10",
              order: 2,
            },
          ],
        },
        {
          id: "math_10_ch11",
          title: "Constructions",
          subject: "Mathematics",
          classLevel: "10th",
          description: "Tangents to Circle, Division of a Line Segment",
          weightage: 3,
          topics: [
            {
              id: "topic_math_10_11_1",
              title: "Tangents to Circle",
              chapterId: "math_10_ch11",
              order: 1,
            },
            {
              id: "topic_math_10_11_2",
              title: "Division of a Line Segment",
              chapterId: "math_10_ch11",
              order: 2,
            },
          ],
        },
        {
          id: "math_10_ch12",
          title: "Areas Related to Circles",
          subject: "Mathematics",
          classLevel: "10th",
          description: "Area of Sector and Segment, Combined Figures",
          weightage: 3,
          topics: [
            {
              id: "topic_math_10_12_1",
              title: "Area of Sector and Segment",
              chapterId: "math_10_ch12",
              order: 1,
            },
            {
              id: "topic_math_10_12_2",
              title: "Combined Figures",
              chapterId: "math_10_ch12",
              order: 2,
            },
          ],
        },
        {
          id: "math_10_ch13",
          title: "Surface Areas and Volumes",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Frustum, Combination of Solids, Volume & Surface Area Problems",
          weightage: 6,
          topics: [
            {
              id: "topic_math_10_13_1",
              title: "Frustum",
              chapterId: "math_10_ch13",
              order: 1,
            },
            {
              id: "topic_math_10_13_2",
              title: "Combination of Solids",
              chapterId: "math_10_ch13",
              order: 2,
            },
            {
              id: "topic_math_10_13_3",
              title: "Volume & Surface Area Problems",
              chapterId: "math_10_ch13",
              order: 3,
            },
          ],
        },
        {
          id: "math_10_ch14",
          title: "Statistics",
          subject: "Mathematics",
          classLevel: "10th",
          description:
            "Mean (Direct, Assumed Mean, Step Deviation), Mode, Median, Graphs",
          weightage: 6,
          topics: [
            {
              id: "topic_math_10_14_1",
              title: "Mean (Direct, Assumed Mean, Step Deviation)",
              chapterId: "math_10_ch14",
              order: 1,
            },
            {
              id: "topic_math_10_14_2",
              title: "Mode",
              chapterId: "math_10_ch14",
              order: 2,
            },
            {
              id: "topic_math_10_14_3",
              title: "Median",
              chapterId: "math_10_ch14",
              order: 3,
            },
            {
              id: "topic_math_10_14_4",
              title: "Graphs",
              chapterId: "math_10_ch14",
              order: 4,
            },
          ],
        },
        {
          id: "math_10_ch15",
          title: "Probability",
          subject: "Mathematics",
          classLevel: "10th",
          description: "Experimental Probability, Simple Events",
          weightage: 3,
          topics: [
            {
              id: "topic_math_10_15_1",
              title: "Experimental Probability",
              chapterId: "math_10_ch15",
              order: 1,
            },
            {
              id: "topic_math_10_15_2",
              title: "Simple Events",
              chapterId: "math_10_ch15",
              order: 2,
            },
          ],
        },
      ],
      Science: [
        {
          id: "sci_10_ch1",
          title: "Chemical Reactions and Equations",
          subject: "Science",
          classLevel: "10th",
          description:
            "Types of Chemical Reactions, Balancing Equations, Corrosion and Rancidity",
          weightage: 4,
          topics: [
            {
              id: "topic_sci_10_1_1",
              title: "Types of Chemical Reactions",
              chapterId: "sci_10_ch1",
              order: 1,
            },
            {
              id: "topic_sci_10_1_2",
              title: "Balancing Equations",
              chapterId: "sci_10_ch1",
              order: 2,
            },
            {
              id: "topic_sci_10_1_3",
              title: "Corrosion",
              chapterId: "sci_10_ch1",
              order: 3,
            },
            {
              id: "topic_sci_10_1_4",
              title: "Rancidity",
              chapterId: "sci_10_ch1",
              order: 4,
            },
          ],
        },
        {
          id: "sci_10_ch2",
          title: "Acids, Bases and Salts",
          subject: "Science",
          classLevel: "10th",
          description:
            "pH Scale, Indicators, Reactions of Acids & Bases, Common Salts",
          weightage: 3,
          topics: [
            {
              id: "topic_sci_10_2_1",
              title: "pH Scale",
              chapterId: "sci_10_ch2",
              order: 1,
            },
            {
              id: "topic_sci_10_2_2",
              title: "Indicators",
              chapterId: "sci_10_ch2",
              order: 2,
            },
            {
              id: "topic_sci_10_2_3",
              title: "Reactions of Acids & Bases",
              chapterId: "sci_10_ch2",
              order: 3,
            },
            {
              id: "topic_sci_10_2_4",
              title: "Common Salts",
              chapterId: "sci_10_ch2",
              order: 4,
            },
          ],
        },
        {
          id: "sci_10_ch3",
          title: "Metals and Non-Metals",
          subject: "Science",
          classLevel: "10th",
          description:
            "Physical & Chemical Properties, Ionic Compounds, Corrosion Prevention",
          weightage: 3,
          topics: [
            {
              id: "topic_sci_10_3_1",
              title: "Physical & Chemical Properties",
              chapterId: "sci_10_ch3",
              order: 1,
            },
            {
              id: "topic_sci_10_3_2",
              title: "Ionic Compounds",
              chapterId: "sci_10_ch3",
              order: 2,
            },
            {
              id: "topic_sci_10_3_3",
              title: "Corrosion Prevention",
              chapterId: "sci_10_ch3",
              order: 3,
            },
          ],
        },
        {
          id: "sci_10_ch4",
          title: "Carbon and Its Compounds",
          subject: "Science",
          classLevel: "10th",
          description:
            "Covalent Bonding, Functional Groups, Ethanol & Ethanoic Acid, Soap & Detergent",
          weightage: 5,
          topics: [
            {
              id: "topic_sci_10_4_1",
              title: "Covalent Bonding",
              chapterId: "sci_10_ch4",
              order: 1,
            },
            {
              id: "topic_sci_10_4_2",
              title: "Functional Groups",
              chapterId: "sci_10_ch4",
              order: 2,
            },
            {
              id: "topic_sci_10_4_3",
              title: "Ethanol & Ethanoic Acid",
              chapterId: "sci_10_ch4",
              order: 3,
            },
            {
              id: "topic_sci_10_4_4",
              title: "Soap & Detergent",
              chapterId: "sci_10_ch4",
              order: 4,
            },
          ],
        },
        {
          id: "sci_10_ch5",
          title: "Life Processes",
          subject: "Science",
          classLevel: "10th",
          description: "Nutrition, Respiration, Transportation, Excretion",
          weightage: 7,
          topics: [
            {
              id: "topic_sci_10_5_1",
              title: "Nutrition",
              chapterId: "sci_10_ch5",
              order: 1,
            },
            {
              id: "topic_sci_10_5_2",
              title: "Respiration",
              chapterId: "sci_10_ch5",
              order: 2,
            },
            {
              id: "topic_sci_10_5_3",
              title: "Transportation",
              chapterId: "sci_10_ch5",
              order: 3,
            },
            {
              id: "topic_sci_10_5_4",
              title: "Excretion",
              chapterId: "sci_10_ch5",
              order: 4,
            },
          ],
        },
        {
          id: "sci_10_ch6",
          title: "Control and Coordination",
          subject: "Science",
          classLevel: "10th",
          description:
            "Nervous System, Hormones in Animals & Plants, Reflex Actions",
          weightage: 4,
          topics: [
            {
              id: "topic_sci_10_6_1",
              title: "Nervous System",
              chapterId: "sci_10_ch6",
              order: 1,
            },
            {
              id: "topic_sci_10_6_2",
              title: "Hormones in Animals & Plants",
              chapterId: "sci_10_ch6",
              order: 2,
            },
            {
              id: "topic_sci_10_6_3",
              title: "Reflex Actions",
              chapterId: "sci_10_ch6",
              order: 3,
            },
          ],
        },
        {
          id: "sci_10_ch7",
          title: "How do Organisms Reproduce?",
          subject: "Science",
          classLevel: "10th",
          description:
            "Asexual & Sexual Reproduction, Human Reproductive System",
          weightage: 3,
          topics: [
            {
              id: "topic_sci_10_7_1",
              title: "Asexual Reproduction",
              chapterId: "sci_10_ch7",
              order: 1,
            },
            {
              id: "topic_sci_10_7_2",
              title: "Sexual Reproduction",
              chapterId: "sci_10_ch7",
              order: 2,
            },
            {
              id: "topic_sci_10_7_3",
              title: "Human Reproductive System",
              chapterId: "sci_10_ch7",
              order: 3,
            },
          ],
        },
        {
          id: "sci_10_ch8",
          title: "Heredity",
          subject: "Science",
          classLevel: "10th",
          description: "Mendel's Experiments, Traits, Sex Determination",
          weightage: 4,
          topics: [
            {
              id: "topic_sci_10_8_1",
              title: "Mendel's Experiments",
              chapterId: "sci_10_ch8",
              order: 1,
            },
            {
              id: "topic_sci_10_8_2",
              title: "Traits",
              chapterId: "sci_10_ch8",
              order: 2,
            },
            {
              id: "topic_sci_10_8_3",
              title: "Sex Determination",
              chapterId: "sci_10_ch8",
              order: 3,
            },
          ],
        },
        {
          id: "sci_10_ch9",
          title: "Light – Reflection and Refraction",
          subject: "Science",
          classLevel: "10th",
          description:
            "Mirrors & Lenses, Ray Diagrams, Mirror & Lens Formula, Magnification",
          weightage: 7,
          topics: [
            {
              id: "topic_sci_10_9_1",
              title: "Mirrors & Lenses",
              chapterId: "sci_10_ch9",
              order: 1,
            },
            {
              id: "topic_sci_10_9_2",
              title: "Ray Diagrams",
              chapterId: "sci_10_ch9",
              order: 2,
            },
            {
              id: "topic_sci_10_9_3",
              title: "Mirror & Lens Formula",
              chapterId: "sci_10_ch9",
              order: 3,
            },
            {
              id: "topic_sci_10_9_4",
              title: "Magnification",
              chapterId: "sci_10_ch9",
              order: 4,
            },
          ],
        },
        {
          id: "sci_10_ch10",
          title: "The Human Eye and the Colourful World",
          subject: "Science",
          classLevel: "10th",
          description: "Defects of Vision, Atmospheric Refraction, Dispersion",
          weightage: 3,
          topics: [
            {
              id: "topic_sci_10_10_1",
              title: "Defects of Vision",
              chapterId: "sci_10_ch10",
              order: 1,
            },
            {
              id: "topic_sci_10_10_2",
              title: "Atmospheric Refraction",
              chapterId: "sci_10_ch10",
              order: 2,
            },
            {
              id: "topic_sci_10_10_3",
              title: "Dispersion",
              chapterId: "sci_10_ch10",
              order: 3,
            },
          ],
        },
        {
          id: "sci_10_ch11",
          title: "Electricity",
          subject: "Science",
          classLevel: "10th",
          description:
            "Ohm's Law, Resistance, Series & Parallel, Power, Circuit Diagram",
          weightage: 7,
          topics: [
            {
              id: "topic_sci_10_11_1",
              title: "Ohm's Law",
              chapterId: "sci_10_ch11",
              order: 1,
            },
            {
              id: "topic_sci_10_11_2",
              title: "Resistance",
              chapterId: "sci_10_ch11",
              order: 2,
            },
            {
              id: "topic_sci_10_11_3",
              title: "Series & Parallel",
              chapterId: "sci_10_ch11",
              order: 3,
            },
            {
              id: "topic_sci_10_11_4",
              title: "Power",
              chapterId: "sci_10_ch11",
              order: 4,
            },
            {
              id: "topic_sci_10_11_5",
              title: "Circuit Diagram",
              chapterId: "sci_10_ch11",
              order: 5,
            },
          ],
        },
        {
          id: "sci_10_ch12",
          title: "Magnetic Effects of Electric Current",
          subject: "Science",
          classLevel: "10th",
          description:
            "Magnetic Field, Right-Hand Thumb Rule, Fleming's Rules, Electromagnet",
          weightage: 6,
          topics: [
            {
              id: "topic_sci_10_12_1",
              title: "Magnetic Field",
              chapterId: "sci_10_ch12",
              order: 1,
            },
            {
              id: "topic_sci_10_12_2",
              title: "Right-Hand Thumb Rule",
              chapterId: "sci_10_ch12",
              order: 2,
            },
            {
              id: "topic_sci_10_12_3",
              title: "Fleming's Rules",
              chapterId: "sci_10_ch12",
              order: 3,
            },
            {
              id: "topic_sci_10_12_4",
              title: "Electromagnet",
              chapterId: "sci_10_ch12",
              order: 4,
            },
          ],
        },
        {
          id: "sci_10_ch13",
          title: "Sources of Energy",
          subject: "Science",
          classLevel: "10th",
          description:
            "Renewable & Non-Renewable Energy Sources, Environmental Impact",
          weightage: 2,
          topics: [
            {
              id: "topic_sci_10_13_1",
              title: "Renewable & Non-Renewable Energy Sources",
              chapterId: "sci_10_ch13",
              order: 1,
            },
            {
              id: "topic_sci_10_13_2",
              title: "Environmental Impact",
              chapterId: "sci_10_ch13",
              order: 2,
            },
          ],
        },
        {
          id: "sci_10_ch14",
          title: "Our Environment",
          subject: "Science",
          classLevel: "10th",
          description: "Food Chains, Trophic Levels, Ozone Layer",
          weightage: 3,
          topics: [
            {
              id: "topic_sci_10_14_1",
              title: "Food Chains",
              chapterId: "sci_10_ch14",
              order: 1,
            },
            {
              id: "topic_sci_10_14_2",
              title: "Trophic Levels",
              chapterId: "sci_10_ch14",
              order: 2,
            },
            {
              id: "topic_sci_10_14_3",
              title: "Ozone Layer",
              chapterId: "sci_10_ch14",
              order: 3,
            },
          ],
        },
        {
          id: "sci_10_ch15",
          title: "Management of Natural Resources",
          subject: "Science",
          classLevel: "10th",
          description: "5R Principle, Water & Forest Conservation",
          weightage: 2,
          topics: [
            {
              id: "topic_sci_10_15_1",
              title: "5R Principle",
              chapterId: "sci_10_ch15",
              order: 1,
            },
            {
              id: "topic_sci_10_15_2",
              title: "Water & Forest Conservation",
              chapterId: "sci_10_ch15",
              order: 2,
            },
          ],
        },
      ],
      English: [
        {
          id: "eng_10_ch1",
          title: "A Letter to God",
          subject: "English",
          classLevel: "10th",
          topics: [
            {
              id: "topic_eng_10_1",
              title: "Character Study",
              chapterId: "eng_10_ch1",
              order: 1,
            },
            {
              id: "topic_eng_10_2",
              title: "Theme Analysis",
              chapterId: "eng_10_ch1",
              order: 2,
            },
          ],
        },
      ],
      "Social Science": [],
    },
  },
};
